export const skills = [
  "Django",
  "React Native",
  "Angular",
  "Vue.js",
  "Ember.js",
  "Backbone.js",
  "Svelte",
  "jQuery",
  "Bootstrap",
  "Tailwind CSS",
  "HTML5",
  "CSS3",
  "Sass",
  "LESS",
  "Stylus",
  "Node.js",
  "Express.js",
  "Koa.js",
  "NestJS",
  "AdonisJS",
  "Meteor.js",
  "GraphQL",
  "Apollo Client",
  "Apollo Server",
  "RESTful APIs",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Firebase",
  "Redis",
  "Elasticsearch",
  "CouchDB",
  "Oracle",
  "Microsoft SQL Server",
  "PL/SQL",
  "NoSQL",
  "Cassandra",
  "Hadoop",
  "Spark",
  "Kafka",
  "RabbitMQ",
  "ZeroMQ",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud",
  "Microsoft Azure",
  "Heroku",
  "DigitalOcean",
  "Linode",
  "Netlify",
  "Vercel",
  "Git",
  "SVN",
  "Mercurial",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "GitHub Actions",
  "Bitbucket Pipelines",
  "Jira",
  "Trello",
  "Asana",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "WebSockets",
  "Socket.io",
  "SignalR",
  "gRPC",
  "OAuth",
  "JWT",
  "OAuth2",
  "OpenID Connect",
  "SAML",
  "OAuth2.0",
  "OAuth1.0",
  "JSON Web Tokens",
  "REST",
  "SOAP",
  "gRPC-Web",
  "XML",
  "YAML",
  "Protocol Buffers",
  "GraphQL SDL",
  "OpenAPI",
  "RAML",
  "Async/Await",
  "Promises",
  "Observables",
  "RxJS",
  "Redux",
  "MobX",
  "Flux",
  "MVC",
  "MVVM",
  "VIPER",
  "Clean Architecture",
  "Domain-Driven Design",
  "Event-Driven Architecture",
  "Microservices",
  "Serverless",
  "Monolithic Architecture",
  "Containerization",
  "Continuous Integration (CI)",
  "Continuous Delivery (CD)",
  "Continuous Deployment (CD)",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Lean Software Development",
  "Extreme Programming (XP)",
  "Pair Programming",
  "Code Review",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Performance Testing",
  "Security Testing",
  "Accessibility Testing",
  "Cross-Browser Testing",
  "Responsive Web Design",
  "Progressive Web Apps (PWAs)",
  "Single Page Applications (SPAs)",
  "Multi-Page Applications (MPAs)",
  "Static Site Generators (SSGs)",
  "Content Management Systems (CMS)",
  "Headless CMS",
  "Jamstack",
  "Fullstack Development",
  "Backend Development",
  "Frontend Development",
  "Mobile Development",
  "Web Development",
  "Desktop Development",
  "Game Development",
  "Cloud Computing",
  "Artificial Intelligence (AI)",
  "Machine Learning (ML)",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Reinforcement Learning",
  "Predictive Analytics",
  "Data Engineering",
  "Data Science",
  "Big Data",
  "Business Intelligence (BI)",
  "Data Visualization",
  "Data Warehousing",
  "ETL (Extract, Transform, Load)",
  "Data Mining",
  "Statistical Analysis",
  "Quantitative Analysis",
  "Qualitative Analysis",
  "Exploratory Data Analysis (EDA)",
  "Predictive Modeling",
  "Supervised Learning",
  "Unsupervised Learning",
  "Semi-Supervised Learning",
  "Reinforcement Learning",
  "Classification",
  "Regression",
  "Clustering",
  "Dimensionality Reduction",
  "Anomaly Detection",
  "Time Series Analysis",
  "Survival Analysis",
  "Deep Learning",
  "Neural Networks",
  "Convolutional Neural Networks (CNNs)",
  "Recurrent Neural Networks (RNNs)",
  "Long Short-Term Memory Networks (LSTMs)",
  "Generative Adversarial Networks (GANs)",
  "Autoencoders",
  "Transformer Networks",
  "BERT",
  "GPT",
];

export const techies = [
  {
    id: 1,
    name: "John Doe",
    username: "johndoe",
    title: "Software Engineer",
    location: "Lagos, Nigeria",
    school: "University of Lagos",
    avatar: "https://bit.ly/3zr9fjM",
    skills: ["React", "Node", "TypeScript", "GraphQL", "AWS"],
    bio: "I am a software engineer with over 5 years of experience building web applications.",
    github: "https://github.com/devvspaces/",
    twitter: "https://twitter.com/devvspaces",
    linkedin: "https://linkedin.com/in/devvspaces",
    dribble: "",
  },
  {
    id: 2,
    name: "Jane Smith",
    username: "janesmith",
    title: "Full Stack Developer",
    location: "New York City, USA",
    avatar: "https://bit.ly/3g8jpxS",
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "Express.js"],
    bio: "Experienced full stack developer passionate about creating scalable and efficient web applications.",
    github: "https://github.com/janesmith",
    twitter: "https://twitter.com/janesmith_dev",
    linkedin: "https://linkedin.com/in/janesmith",
    website: "https://janesmith.dev",
  },
  {
    id: 3,
    name: "Ahmed Hassan",
    username: "ahmedhassan",
    title: "Frontend Developer",
    location: "Cairo, Egypt",
    avatar: "https://bit.ly/3GsF2h1",
    skills: ["HTML", "CSS", "JavaScript", "Vue.js", "Tailwind CSS"],
    bio: "Passionate about crafting beautiful and responsive user interfaces with the latest web technologies.",
    github: "https://github.com/ahmedhassan",
    linkedin: "https://linkedin.com/in/ahmedhassan",
    dribble: "https://dribbble.com/ahmedhassan",
  },
  {
    id: 4,
    name: "Anna Lee",
    username: "annalee",
    title: "Backend Developer",
    location: "Tokyo, Japan",
    avatar: "https://bit.ly/3IyYGz2",
    skills: ["Python", "Django", "SQL", "RESTful APIs", "Docker"],
    bio: "Experienced backend developer specialized in building robust and scalable server-side applications.",
    github: "https://github.com/annalee_dev",
    linkedin: "https://linkedin.com/in/annalee",
  },
  {
    id: 5,
    name: "Carlos Rodriguez",
    username: "carlosrodriguez",
    title: "DevOps Engineer",
    location: "São Paulo, Brazil",
    avatar: "https://bit.ly/3GpXuQ0",
    skills: ["Kubernetes", "Docker", "Jenkins", "AWS", "Terraform"],
    bio: "DevOps enthusiast with a focus on automating deployment pipelines and optimizing infrastructure.",
    github: "https://github.com/carlosrodriguez",
    linkedin: "https://linkedin.com/in/carlosrodriguez",
    dribble: "https://dribbble.com/carlosrodriguez",
  },
  {
    id: 6,
    name: "Lina Kim",
    username: "linakim",
    title: "UI/UX Designer",
    location: "Seoul, South Korea",
    avatar: "https://bit.ly/3td2Ar5",
    skills: ["Adobe XD", "Figma", "Sketch", "User Research", "Prototyping"],
    bio: "Passionate about creating intuitive and visually appealing user experiences through design.",
    linkedin: "https://linkedin.com/in/linakim",
  },
  {
    id: 7,
    name: "Mohammed Ali",
    username: "mohammedali",
    title: "Machine Learning Engineer",
    location: "Mumbai, India",
    avatar: "https://bit.ly/3zohOPP",
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Natural Language Processing",
    ],
    bio: "Machine learning enthusiast with a focus on developing AI solutions for real-world problems.",
    github: "https://github.com/mohammedali_ml",
    linkedin: "https://linkedin.com/in/mohammedali",
    dribble: "https://dribbble.com/mohammedali",
  },
  {
    id: 8,
    name: "Emily Chen",
    username: "emilychen",
    title: "Data Scientist",
    location: "San Francisco, USA",
    avatar: "https://bit.ly/3GyWwdM",
    skills: ["Python", "R", "SQL", "Machine Learning", "Data Visualization"],
    bio: "Data-driven problem solver with expertise in statistical analysis and predictive modeling.",
    github: "https://github.com/emilychen_ds",
    linkedin: "https://linkedin.com/in/emilychen",
  },
  {
    id: 9,
    name: "David Johnson",
    username: "davidjohnson",
    title: "Cybersecurity Analyst",
    location: "London, UK",
    avatar: "https://bit.ly/3vjUrVt",
    skills: [
      "Network Security",
      "Penetration Testing",
      "SIEM",
      "Ethical Hacking",
      "Incident Response",
    ],
    bio: "Experienced cybersecurity professional dedicated to safeguarding digital assets and networks.",
    github: "https://github.com/davidjohnson_sec",
    linkedin: "https://linkedin.com/in/davidjohnson",
    dribble: "https://dribbble.com/davidjohnson",
  },
  {
    id: 10,
    name: "Sophia Wang",
    username: "sophiawang",
    title: "Cloud Engineer",
    location: "Shanghai, China",
    avatar: "https://bit.ly/3Lz2rvV",
    skills: [
      "AWS",
      "Azure",
      "Google Cloud",
      "DevOps",
      "Infrastructure as Code",
    ],
    bio: "Cloud enthusiast passionate about designing and implementing scalable and reliable cloud solutions.",
    linkedin: "https://linkedin.com/in/sophiawang",
  },
  {
    id: 11,
    name: "Michael Davis",
    username: "michaeldavis",
    title: "Mobile App Developer",
    location: "Los Angeles, USA",
    avatar: "https://bit.ly/3Lw1p5X",
    skills: [
      "iOS Development",
      "Swift",
      "Android Development",
      "Kotlin",
      "Flutter",
    ],
    bio: "Experienced mobile app developer with a focus on creating engaging and user-friendly applications.",
    github: "https://github.com/michaeldavis",
    linkedin: "https://linkedin.com/in/michaeldavis",
    dribble: "https://dribbble.com/michaeldavis",
  },
  {
    id: 12,
    name: "Maria Garcia",
    username: "mariagarcia",
    title: "DevOps Engineer",
    location: "Madrid, Spain",
    avatar: "https://bit.ly/3wA7zRb",
    skills: ["Kubernetes", "Docker", "Jenkins", "AWS", "Terraform"],
    bio: "DevOps enthusiast with expertise in automating deployment processes and optimizing infrastructure.",
    github: "https://github.com/mariagarcia",
    linkedin: "https://linkedin.com/in/mariagarcia",
  },
];
